FROM python:3.9.18-slim-bullseye

WORKDIR /app

# 依存関係をコピーしてインストール
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# アプリケーションコードをコピー
COPY ./app/ .

# コンテナ起動時にマイグレーションを実行し、FastAPI を起動
CMD ["sh", "-c", "python init_db.py && uvicorn main:app --host 0.0.0.0 --port 8080 --reload"]